### ISSUE TITLE
Please fix the license

### ISSUE THREAD

**Issue by a-m-s** [projecthamster/hamster-shell-extension#182] opened 2017-05-25 13:23 UTC
The project has no COPYING or LICENSE file, and the license terms inside the source files are uneven:
* convenience.js has an unnamed license
* extension.js is marked GPL, and refers to a non-existent COPYING file.
* prefs.js and stuff.js lack any kind of copyright or license at all (so, technically, nobody is permitted to download it).

Legally, the license in convenience.js cannot be removed (unless you can get all the contributors to agree to something different), but the terms of the GPL mean that it must cover all the files distributed together in any case. By my understanding, although IANAL, this means the project has been effectively GPL all along.

The following steps are necessary:
* Import a copy of the [GPL](https://www.gnu.org/licenses/licenses.html#GPL) as COPYING.
* Add the appropriate copyright and license headers to each source file.

Having done this you can remove the distasteful CLA; the GPL has words about copyright, patents, and warranties that are sufficient to cover future contributions on their own.

Pull requests like #181 can then be merged if and when the author rebases the patch, thus licensing it under the GPL.

**Comment by elbenfreund** [comment] 2017-06-20 14:44
I agree that sorting our the licensing madness needs to be done, although I doubt there will be a right/clean way to do this. This topic has been neglected for years and all we can hope for is a clean cut and moving forward in a better fashion.

However, as important adding the relevant licensing information is, it is totally unrelated to the problem addressed by the CLA. For a basic introduction please see clahub's [docs](https://www.clahub.com/pages/why_cla).

Whilst I (like most FLOSS developers) resent the legaleze overhead introduced by a CLA the truth is that licensing a collaborative codebase is moot if copyright is not assigned as well (via a CLA).
I understand you think, committing also assigns copyright, but it simply does not. Without assigned copyright however, the license is not enforceable and hence obsolete anyway.

Please feel invited to discuss the matter, but for a general overview and introduction to this issue I best refer to the existing resource available on the net.

**Comment by elbenfreund** [comment] 2017-06-20 14:52
Dupe of #135 Please lets move the discussion (if there will be one) to the mailing list or #135

**Closed by elbenfreund** 2017-06-20 14:52 UTC
Labels: duplicate
