### ISSUE TITLE
Not working on fedora 25

### ISSUE THREAD

**Issue by psychoslave** [projecthamster/hamster-shell-extension#169] opened 2017-02-23 08:54 UTC
Hi, 
On a fresh new install of Fedora 25, the application is said incompatible with gnome 3.22.3. Using the "Compatible with > all version", I can find it, but when I click install, after answering yes to the validation pop up, nothing seems to happen.

**Comment by border0464111** [comment] 2017-02-23 11:52
Hi thx for reaching out, I think it's a known bug, it been fixed in the developement branch but not released in stable yet. 

You can take a look at the specific commit regarding this bug here, it been quite easy to fix ;) 

https://github.com/projecthamster/hamster-shell-extension/commit/571c0926392be4842388c13406d5c32a05340685

**Comment by elbenfreund** [comment] 2017-02-23 20:16
Will close as solved for now. Please feel free to let us know if the fix did not work for you and we should reopen.

**Comment by psychoslave** [comment] 2017-02-27 14:10
Actually, it's seems that the application is not installed at all, as there is no hamster subdirectory in ~/.local/share/gnome-shell/extensions. Should I manually install it from the git repository, and if so, what branch/commit should I set ~/.local/share/gnome-shell/extensions/hamster@projecthamster.wordpress.com after a `git clone https://github.com/projecthamster/hamster-shell-extension.git "~/.local/share/gnome-shell/extensions/hamster@projecthamster.wordpress.com"`? Should I run any other command too?

**Comment by elbenfreund** [comment] 2017-02-27 14:14
For the most recent (and still quite stable afaik) version you could try the ``develop`` branch.
After cloning to the proper location you may have to restart the shell with ``Alt+F2`` -> ``r``.
Let us know how things went :)

**Comment by psychoslave** [comment] 2017-02-27 17:00
After passing to *develop*, here are a few extra step currently required to compile on Fedora 25:

-  edit Makefile and add `--user` to `pip install` command, otherwise it will complain that it can't uninstall the current version. The `--user` flag make the installation in `~/.local/lib/pythonx.y/site-packages`.
- launch `mkdir dist` (or add it in the dist target dependencies)
- run `make develop && make collect && make compile && make dist`

[This diff file changes the Makefile according to that few remarks](https://github.com/projecthamster/hamster-shell-extension/files/804377/hamster_makfile.diff.txt).

**Comment by psychoslave** [comment] 2017-02-27 17:04
By the way, neither the symbolic link nor the dist archive will enable the extension successfully.

**Comment by elbenfreund** [comment] 2017-02-27 18:38
Thanks for you investigation. In fact, the makefile needs some serious cleaning up.
What has me wondering is your last line. ``make dist`` should run the ``compile`` and ``collect`` [as dependencies](https://github.com/projecthamster/hamster-shell-extension/blob/develop/Makefile#L61). Are you sure calling them explicitly was needed?

With regards to the extention still not working: I assume the output of ``gnome-shell --version`` is still ``3.22.3``?
does your ``/.local/share/gnome-shell/extensions/hamster@projecthamster.wordpress.com/``dir look something contain ``metadata.json`` and ``extension.js`` at the root level?

**Comment by psychoslave** [comment] 2017-02-28 09:26
>Are you sure calling them explicitly was needed?

No, actually I didn't investigated the dependencies tree, I just lazily ran each task until I found a working order, as there are no instruction in the README file.

Here is how the installation looks like currently
```
% gnome-shell --version
GNOME Shell 3.22.3

% la ~/.local/share/gnome-shell/extensions/                                     
total 12
drwxrwxr-x. 3 psychoslave psychoslave 4096 27 févr. 15:18 .
drwx------. 3 psychoslave psychoslave 4096 28 févr. 10:19 ..
lrwxrwxrwx. 1 psychoslave psychoslave   50 27 févr. 15:17 hamster@projecthamster.wordpress.com -> /home/psychoslave/Projets/hamster-shell-extension/
drwxrwxr-x. 4 psychoslave psychoslave 4096 23 févr. 17:35 suspend-button@laserb

% la ~/.local/share/gnome-shell/extensions/hamster@projecthamster.wordpress.com/
total 128
drwxr-xr-x. 8 psychoslave psychoslave  4096 28 févr. 10:19 .
drwxrwxr-x. 8 psychoslave psychoslave  4096 27 févr. 17:09 ..
-rw-r--r--. 1 psychoslave psychoslave   998 27 févr. 15:22 AUTHORS.rst
drwxr-xr-x. 6 psychoslave psychoslave  4096 27 févr. 18:00 build
-rw-r--r--. 1 psychoslave psychoslave  2648 27 févr. 15:22 CONTRIBUTING.rst
drwxr-xr-x. 5 psychoslave psychoslave  4096 27 févr. 18:02 data
drwxr-xr-x. 2 psychoslave psychoslave  4096 27 févr. 18:00 dist
drwxr-xr-x. 2 psychoslave psychoslave  4096 27 févr. 15:22 docs
-rw-r--r--. 1 psychoslave psychoslave   286 27 févr. 15:22 .editorconfig
drwxr-xr-x. 3 psychoslave psychoslave  4096 27 févr. 15:22 extension
drwxr-xr-x. 8 psychoslave psychoslave  4096 28 févr. 10:22 .git
-rw-r--r--. 1 psychoslave psychoslave    35 27 févr. 15:22 .gitignore
-rw-r--r--. 1 psychoslave psychoslave 59764 27 févr. 15:12 hamster@projecthamster.wordpress.com.zip
-rw-r--r--. 1 psychoslave psychoslave  2035 27 févr. 15:22 HISTORY.rst
-rw-r--r--. 1 psychoslave psychoslave  2412 27 févr. 17:56 Makefile
-rw-r--r--. 1 psychoslave psychoslave  1549 27 févr. 15:22 README.rst
-rw-r--r--. 1 psychoslave psychoslave   213 27 févr. 15:22 requirements.pip
-rw-r--r--. 1 psychoslave psychoslave   244 27 févr. 15:22 setup.cfg
```

**Comment by border0464111** [comment] 2017-03-03 21:55
I see, The content of ``~/.local/share/gnome-shell/extensions/hamster@projecthamster.wordpress.com/hamster@projecthamster.wordpress.com.zip``

should be inside ``~/.local/share/gnome-shell/extensions/hamster@projecthamster.wordpress.com``
instead of the actual content you have atm.

**Comment by psychoslave** [comment] 2017-03-06 07:55
Well unfortunately, it's still doesn't work on the Fedora 25 worksation using this zip. Manual install won't appear in the list of extension, and trying to install the zip with gnome-tweak lead to an "unvalid extentions" message in the notification bar.

**Comment by waldyd** [comment] 2017-04-03 16:17
The following is being prompted by journalctl:

```
gnome-shell[2062]: JS LOG: Extension "hamster@projecthamster.wordpress.com" had error: Gio.IOErrorEnum: Error calling StartServiceByName for org.gnome.Hamster: Timeout was reached
dbus-daemon[1968]: [session uid=1000 pid=1968] Activating service name='org.gnome.GConf' requested by ':1.55' (uid=1000 pid=2231 comm="python2 /usr/bin/hamster-service " label="unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023")
org.gnome.Shell.desktop[2062]: Window manager warning: Trying to remove non-existent keybinding "show-hamster-dropdown".
gnome-shell[2062]: JS LOG: Extension "hamster@projecthamster.wordpress.com" had error: TypeError: this.extension is null
```

**Comment by breakpoint8088** [comment] 2017-07-12 22:27
I think this may actually be a Wayland issue.  Fedora 26 uses Wayland by default ON A CLEAN INSTALL, but users upgrading from previous versions may still be using it on XOrg.

I am using Fedora 26, upgrading from Fedora 25, and I had to add the '.24 version and fix the "var" declarations.  I can now use the extension nicely under XOrg, but it will crash Wayland on startup if I attempt to use it under Wayland.

I think this may be related to this issue:
https://github.com/projecthamster/hamster-shell-extension/issues/159

...which, at the time, was resolvable by this change set:
https://github.com/jasuarez/hamster-shell-extension/commit/61286f0

However, it appears that event binding has changed significantly, and I'm still trying to see if I can figure out how to fix those changes.

**Comment by breakpoint8088** [comment] 2017-07-12 22:31
**In any case, as near as I can tell, the root issues are:**

- Under Wayland, the shell extension may be starting earlier than Hamster itself.  The extension needs a delay before attempting to start.  This is not unique to Hamster and is breaking a bunch of other plugins too, but the workaround should be fairly simple.
- The list of GNOME Shell versions the extension claims support for needs to be updated to include 22 and 24, if you haven't yet.
- Some redundant "var" declarations cause problems; these need to be fixed if you haven't already patched them.

All of this is complicated by these factors:
- Fedora CAN use Wayland, but not everybody DOES.
- A lot of people don't really reliably know if they're running Wayland or not.
- In Wayland, you cannot restart GNOME Shell using ALT-F2 "r".  This complicates troubleshooting.
- Looking Glass can hang while attempting to troubleshoot this (though I was able to get far enough to at least see the problem).

**Comment by breakpoint8088** [comment] 2017-07-12 23:22
Oh, and then there's the matter of the Fedora repos attempting to package and provide a version of the hamster backend, but all these recent issues with the shell extension require newer code...

**Comment by elbenfreund** [comment] 2017-07-14 16:48
Dear @breakpoint8088 thank you for this elaborate writeup. I hope to have time to have a look at this during this coming weekend.

**Comment by elbenfreund** [comment] 2017-07-18 15:48
So, first of all: thanks everyone for investing your time into reporting and fixing this.
This issue is actually raising multiple concerns, most of them justefied but easily addressed. I will try to get those out of the way so we can focus on the more interesting bits:
1. ``make dist`` does not ensure that the target dir actually exists. PR #187 will take care of this.
2. pip should be run with ``--user`` flag. It is actually worst than this. There is simply no documentation about the development environment at all. This is raised in the new issue #195  and fixed in PR #196
3. Wrong instructions for manual installation: This addressed in #184

With this out of the way, lets now deal with the actual problem as suggested by @breakpoint8088:
I agree that this is most likely a duplicate of #159 . In order to focus the discussion of this issue I suggest that @breakpoint8088 posts his general analysis of the wayland situation over there as I think it sounds quite accurate and is suitable to avoid a lot of confusion. Is this alright with you @breakpoint8088 ?

About [your last comment](https://github.com/projecthamster/hamster-shell-extension/issues/169#issuecomment-314925336): I am not sure what you mean: the recent change  of the extensions general code layout (aka ``develop``) should not actually change the way we interact with ``legacy hamster``. so swaping the extensin shipped by fedora for the ``0.10.0`` (aka ``develop``). should work in general. In the same spirit: What changes to event handling are you refering to? As I said, the actual logic should not have changed much (for better or worse :/) so far but just the code layout. Can you help out with pointers?

**Comment by elbenfreund** [comment] 2017-10-13 13:53
@psychoslave Are you willing to revisit the situation with the current develop branch? I hope we were able to address several of the issues you brought up. Ideally the only open concern is #159 which at least should now bring up a notification if the relevant hamster dbus services are not up and runnin.

**Comment by elbenfreund** [comment] 2017-11-14 15:13
@psychoslave ping :)

pls let me know if you consider this inappropriate spam!

**Comment by psychoslave** [comment] 2017-11-14 15:31
No problem, I don't consider this as spam at all. Oddly trynig to open the link of this ticket systematically crashed firefox.

Thus said, currently I don't use hamster anymore. Also I doubt I will find much time to test it. I hope you will be able to have other users able to provide you feedback.

**Comment by hpg-mheck** [comment] 2017-11-14 18:42
Hmmm.  Does anyone know who's most actively maintaining Hamster, over all?

**Comment by elbenfreund** [comment] 2017-11-15 14:16
@hpg-mheck what do you mean exactly? I fear you are already talking to us...?! :)

**Comment by elbenfreund** [comment] 2017-11-15 14:22
@psychoslave thanks for getting back to us. Maybe at some later stage you give us try again, there will be a proper major release at some point in the future afterall :)

**Comment by elbenfreund** [comment] 2018-03-11 21:41
Is this issue still relevant? Or have all questions besides the wayland specifics been addressed/solved?
If so, I would like to close this one and focus on the remaining work...

**Comment by elbenfreund** [comment] 2018-03-26 12:24
Will close for now. Please feel free to reopen or create a new issue if the problem persists/reapears.

**Closed by elbenfreund** 2018-03-26 12:24 UTC
Labels: bug, waiting for feedback
