### ISSUE TITLE
Display total time in daily summary (in addition to Category times)

### ISSUE THREAD

**Issue by MTindev** [projecthamster/hamster-shell-extension#199] opened 2017-10-09 14:53 UTC
Hello,

I am only working with the gnome-extension.
Below the "Today's activities", the daily time summary is displayed.

First times, I used the extension without categories (always with @Misc).
The daily time as OK as : 
**Misc : 6h5**

Then I have tried with categories, and the daily summary (is OK too and) looks like :
**Category1: 4h, Category2: 2h5**

It is great and relevant to get information about the time by category.
But I think it would be convenient to keep an eye on the "total daily time" too.
Something like : 
**Category1 : 4h** **Category2 : 2h5**
**Total : 6h5**

In any case, thanks for the current implementation, nice extension.

**Comment by a-m-s** [comment] 2017-10-09 16:33
Duplicate of #78

**Closed** 2017-10-11 05:58 UTC
